<?xml version="1.0" encoding="UTF-8"?>
<testsuites failures="1" skipped="0" tests="7" testsuite_failed="True" time="34.454337" timestamp="2020-02-19T00:22:51.251191">
 <properties>
  <property name="module" value="GatewayNativeClient"/>
  <property name="module" value="FixExchangeEmulator"/>
  <property name="python-module-path" value="Scripts/Gateway/SystemAreas/OrderProcessing/PythonModules"/>
  <property name="python-module-path" value="Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/GroupAccounts/PythonModules"/>
  <property name="python-module-path" value="ScriptKit"/>
  <property name="python-module-path" value="Scripts/Gateway/PythonModules"/>
  <property name="environment-config-repository" value="XML:Scripts/Gateway/EnvConfigs/GatewayTestingEnvironmentConfigRepository.xml"/>
  <property name="modules-cfg-instance" value="SF_ESR1"/>
  <property name="scripts-cfg-instance" value=""/>
  <property name="threads-count" value="1"/>
  <property name="path" value="Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/RFQ"/>
  <property name="host" value="k12sgwcendev31"/>
 </properties>
 <testsuite failures="1" name="RFQ" skipped="0" tests="7" testsuite_failed="True" time="34.454337" timestamp="2020-02-19T00:22:51.251191">
  <testcase name="RFQ01" status="run" time="1.7343190000000002" timestamp="2020-02-19T00:23:03.814258"/>
  <testcase name="RFQ02" status="run" time="5.937736" timestamp="2020-02-19T00:23:05.595442"/>
  <testcase name="RFQ03" status="run" time="1.109417" timestamp="2020-02-19T00:23:11.564408"/>
  <testcase name="RFQ04" status="run" time="0.046891" timestamp="2020-02-19T00:23:12.720696"/>
  <testcase name="RFQ05" status="run" time="0.015714" timestamp="2020-02-19T00:23:12.830085"/>
  <testcase name="RFQ06" status="run" time="11.608655" timestamp="2020-02-19T00:23:12.909387">
   <failure message="Traceback (most recent call last):
  File &quot;C:\xpit.com\applications\ScriptFramework\ScriptKit\Core\Invoker.py&quot;, line 29, in invoke_script
    exec(code, isolated_dict)
  File &quot;Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/RFQ\RFQ06_tc.py&quot;, line 32, in &lt;module&gt;
    SendAndAckQuoteRequest_Rejected(quoteRequest, &quot;Cannot process the order (error code 9). Please contact customer support for assistance&quot;)
  File &quot;Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/RFQ\test_suite_su.py&quot;, line 68, in SendAndAckQuoteRequest_Rejected
    VerifyQuoteRequestAcknowledgement(requestAck, expectedRequestAck)
  File &quot;C:\xpit.com\applications\ScriptFramework\Scripts\Gateway\PythonModules\OrderActionUtils.py&quot;, line 484, in VerifyQuoteRequestAcknowledgement
    exchangeRequest.message, expectedRequest.message, msg.format(&quot;message&quot;))
  File &quot;C:\xpit.com\applications\ScriptFramework\ScriptKit\TestCheck.py&quot;, line 81, in AssertEqualMessage
    raise Failure(msg + &quot;'&quot; + GetStr(a) + &quot;'&quot; + &quot; is not equal to &quot; + &quot;'&quot; + GetStr(b) + &quot;'&quot;)
TestCheck.Failure: QuoteRequestAcknowledgement for requestba78feba-bfe0-4665-bcbb-394bc7bf0725 - wrong message: 'Commodity is disabled for trading at this time' is not equal to 'Cannot process the order (error code 9). Please contact customer support for assistance'
">Traceback (most recent call last):
  File &quot;C:\xpit.com\applications\ScriptFramework\ScriptKit\Core\Invoker.py&quot;, line 29, in invoke_script
    exec(code, isolated_dict)
  File &quot;Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/RFQ\RFQ06_tc.py&quot;, line 32, in &lt;module&gt;
    SendAndAckQuoteRequest_Rejected(quoteRequest, &quot;Cannot process the order (error code 9). Please contact customer support for assistance&quot;)
  File &quot;Scripts/Gateway/SystemAreas/OrderProcessing/RiskEvaluation/Suites/RFQ\test_suite_su.py&quot;, line 68, in SendAndAckQuoteRequest_Rejected
    VerifyQuoteRequestAcknowledgement(requestAck, expectedRequestAck)
  File &quot;C:\xpit.com\applications\ScriptFramework\Scripts\Gateway\PythonModules\OrderActionUtils.py&quot;, line 484, in VerifyQuoteRequestAcknowledgement
    exchangeRequest.message, expectedRequest.message, msg.format(&quot;message&quot;))
  File &quot;C:\xpit.com\applications\ScriptFramework\ScriptKit\TestCheck.py&quot;, line 81, in AssertEqualMessage
    raise Failure(msg + &quot;'&quot; + GetStr(a) + &quot;'&quot; + &quot; is not equal to &quot; + &quot;'&quot; + GetStr(b) + &quot;'&quot;)
TestCheck.Failure: QuoteRequestAcknowledgement for requestba78feba-bfe0-4665-bcbb-394bc7bf0725 - wrong message: 'Commodity is disabled for trading at this time' is not equal to 'Cannot process the order (error code 9). Please contact customer support for assistance'
</failure>
  </testcase>
  <testcase name="RFQ_DSI_1300395543" status="run" time="0.968797" timestamp="2020-02-19T00:23:24.549250"/>
 </testsuite>
</testsuites>